import { MigrationInterface, QueryRunner } from "typeorm";

export class InsertCountries1581670603522 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AD', 'Andorra')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AE', 'United Arab Emirates')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AF', 'Afghanistan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AG', 'Antigua and Barbuda')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AI', 'Anguilla')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AL', 'Albania')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AM', 'Armenia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AO', 'Angola')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AQ', 'Antarctica')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AR', 'Argentina')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AS', 'American Samoa')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AT', 'Austria')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AU', 'Australia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AW', 'Aruba')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AX', 'Åland Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('AZ', 'Azerbaijan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BA', 'Bosnia and Herzegovina')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BB', 'Barbados')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BD', 'Bangladesh')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BE', 'Belgium')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BF', 'Burkina Faso')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BG', 'Bulgaria')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BH', 'Bahrain')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BI', 'Burundi')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BJ', 'Benin')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BL', 'Saint Barthélemy')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BM', 'Bermuda')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BN', 'Brunei Darussalam')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BO', 'Bolivia, Plurinational State of')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BQ', 'Bonaire, Sint Eustatius and Saba')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BR', 'Brazil')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BS', 'Bahamas')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BT', 'Bhutan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BV', 'Bouvet Island')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BW', 'Botswana')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BY', 'Belarus')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('BZ', 'Belize')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CA', 'Canada')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CC', 'Cocos (Keeling) Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CD', 'Congo, Democratic Republic of the')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CF', 'Central African Republic')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CG', 'Congo')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CH', 'Switzerland')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CI', 'Côte d'Ivoire')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CK', 'Cook Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CL', 'Chile')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CM', 'Cameroon')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CN', 'China')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CO', 'Colombia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CR', 'Costa Rica')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CU', 'Cuba')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CV', 'Cabo Verde')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CW', 'Curaçao')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CX', 'Christmas Island')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CY', 'Cyprus')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('CZ', 'Czechia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('DE', 'Germany')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('DJ', 'Djibouti')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('DK', 'Denmark')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('DM', 'Dominica')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('DO', 'Dominican Republic')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('DZ', 'Algeria')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('EC', 'Ecuador')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('EE', 'Estonia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('EG', 'Egypt')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('EH', 'Western Sahara')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('ER', 'Eritrea')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('ES', 'Spain')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('ET', 'Ethiopia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('FI', 'Finland')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('FJ', 'Fiji')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('FK', 'Falkland Islands (Malvinas)')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('FM', 'Micronesia, Federated States of')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('FO', 'Faroe Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('FR', 'France')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GA', 'Gabon')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GB', 'United Kingdom of Great Britain and Northern Ireland')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GD', 'Grenada')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GE', 'Georgia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GF', 'French Guiana')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GG', 'Guernsey')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GH', 'Ghana')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GI', 'Gibraltar')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GL', 'Greenland')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GM', 'Gambia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GN', 'Guinea')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GP', 'Guadeloupe')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GQ', 'Equatorial Guinea')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GR', 'Greece')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GS', 'South Georgia and the South Sandwich Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GT', 'Guatemala')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GU', 'Guam')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GW', 'Guinea-Bissau')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('GY', 'Guyana')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('HK', 'Hong Kong')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('HM', 'Heard Island and McDonald Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('HN', 'Honduras')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('HR', 'Croatia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('HT', 'Haiti')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('HU', 'Hungary')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('ID', 'Indonesia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('IE', 'Ireland')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('IL', 'Israel')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('IM', 'Isle of Man')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('IN', 'India')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('IO', 'British Indian Ocean Territory')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('IQ', 'Iraq')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('IR', 'Iran, Islamic Republic of')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('IS', 'Iceland')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('IT', 'Italy')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('JE', 'Jersey')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('JM', 'Jamaica')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('JO', 'Jordan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('JP', 'Japan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KE', 'Kenya')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KG', 'Kyrgyzstan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KH', 'Cambodia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KI', 'Kiribati')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KM', 'Comoros')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KN', 'Saint Kitts and Nevis')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KP', 'Korea, Democratic People's Republic of')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KR', 'Korea, Republic of')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KW', 'Kuwait')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KY', 'Cayman Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('KZ', 'Kazakhstan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LA', 'Lao People's Democratic Republic')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LB', 'Lebanon')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LC', 'Saint Lucia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LI', 'Liechtenstein')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LK', 'Sri Lanka')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LR', 'Liberia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LS', 'Lesotho')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LT', 'Lithuania')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LU', 'Luxembourg')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LV', 'Latvia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('LY', 'Libya')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MA', 'Morocco')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MC', 'Monaco')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MD', 'Moldova, Republic of')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('ME', 'Montenegro')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MF', 'Saint Martin, (French part)')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MG', 'Madagascar')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MH', 'Marshall Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MK', 'North Macedonia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('ML', 'Mali')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MM', 'Myanmar')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MN', 'Mongolia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MO', 'Macao')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MP', 'Northern Mariana Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MQ', 'Martinique')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MR', 'Mauritania')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MS', 'Montserrat')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MT', 'Malta')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MU', 'Mauritius')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MV', 'Maldives')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MW', 'Malawi')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MX', 'Mexico')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MY', 'Malaysia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('MZ', 'Mozambique')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NA', 'Namibia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NC', 'New Caledonia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NE', 'Niger')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NF', 'Norfolk Island')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NG', 'Nigeria')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NI', 'Nicaragua')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NL', 'Netherlands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NO', 'Norway')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NP', 'Nepal')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NR', 'Nauru')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NU', 'Niue')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('NZ', 'New Zealand')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('OM', 'Oman')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PA', 'Panama')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PE', 'Peru')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PF', 'French Polynesia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PG', 'Papua New Guinea')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PH', 'Philippines')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PK', 'Pakistan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PL', 'Poland')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PM', 'Saint Pierre and Miquelon')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PN', 'Pitcairn')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PR', 'Puerto Rico')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PS', 'Palestine, State of')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PT', 'Portugal')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PW', 'Palau')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('PY', 'Paraguay')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('QA', 'Qatar')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('RE', 'Réunion')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('RO', 'Romania')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('RS', 'Serbia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('RU', 'Russian Federation')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('RW', 'Rwanda')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SA', 'Saudi Arabia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SB', 'Solomon Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SC', 'Seychelles')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SD', 'Sudan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SE', 'Sweden')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SG', 'Singapore')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SH', 'Saint Helena, Ascension and Tristan da Cunha')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SI', 'Slovenia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SJ', 'Svalbard and Jan Mayen')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SK', 'Slovakia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SL', 'Sierra Leone')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SM', 'San Marino')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SN', 'Senegal')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SO', 'Somalia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SR', 'Suriname')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SS', 'South Sudan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('ST', 'Sao Tome and Principe')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SV', 'El Salvador')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SX', 'Sint Maarten, (Dutch part)')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SY', 'Syrian Arab Republic')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('SZ', 'Eswatini')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TC', 'Turks and Caicos Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TD', 'Chad')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TF', 'French Southern Territories')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TG', 'Togo')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TH', 'Thailand')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TJ', 'Tajikistan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TK', 'Tokelau')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TL', 'Timor-Leste')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TM', 'Turkmenistan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TN', 'Tunisia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TO', 'Tonga')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TR', 'Turkey')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TT', 'Trinidad and Tobago')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TV', 'Tuvalu')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TW', 'Taiwan, Province of China')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('TZ', 'Tanzania, United Republic of')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('UA', 'Ukraine')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('UG', 'Uganda')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('UM', 'United States Minor Outlying Islands')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('US', 'United States of America')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('UY', 'Uruguay')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('UZ', 'Uzbekistan')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('VA', 'Holy See')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('VC', 'Saint Vincent and the Grenadines')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('VE', 'Venezuela, Bolivarian Republic of')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('VG', 'Virgin Islands, British')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('VI', 'Virgin Islands, U.S.')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('VN', 'Viet Nam')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('VU', 'Vanuatu')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('WF', 'Wallis and Futuna')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('WS', 'Samoa')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('YE', 'Yemen')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('YT', 'Mayotte')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('ZA', 'South Africa')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('ZM', 'Zambia')`);
      await queryRunner.query(`INSERT INTO \`countries\` (countryId, name) VALUES ('ZW', 'Zimbabwe')`);

    }

    public async down(queryRunner: QueryRunner): Promise<any> {
      await queryRunner.query(`TRUNCATE TABLE \`countries\``);
    }

}
